const projects = [
  {
    id: 'jeffreyco-ecommerce',
    title: 'Jeffreyco E-commerce',
    img: '/project3/project3.webp',
    link: '/projects/jeffreyco-ecommerce',
    date: '2024',
    liveLink: 'https://jeffrey-co.vercel.app/#signin',
    company: 'Jeffreyco',
    primary: '#2D2D2D',
    accentColor: '#FCFBF7',
    secondary: '#F2EEE7',
    fillColor: '#F2F3F4',
    menuColor: 'gold',
    menuFontColor: '#2D2D2D',
    fluidColor: '#0028FF',
    images: [
      {
        src: '/project3/video.mp4',
        tag: 'video',
        isRight: false,
      },
      {
        src: '/project3/7.webp',
        tag: 'small',
        isRight: false,
      },
      {
        src: '/project3/6.webp',
        tag: 'small',
        isRight: true,
      },
      {
        src: '/project3/video2.mp4',
        tag: 'video',
        isRight: false,
      },
      {
        src: '/project3/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project3/5.webp',
        tag: 'small',
        isRight: false,
      },
      {
        src: '/project3/8.webp',
        tag: 'small',
        isRight: true,
      },
      {
        src: '/project3/2.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project3/3.webp',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'Developed a fully responsive e-commerce frontend application using Next.js 14, TypeScript, and modern web technologies. Converted Figma designs into a production-ready web application featuring modern tech stack with Next.js 14 App Router, TypeScript, Tailwind CSS, and Redux for state management.',
      'Enhanced UX with smooth animations using Framer Motion and accessible UI components using ShadCN UI. Implemented comprehensive e-commerce features including shopping cart functionality, product browsing, and responsive design across all devices.',
    ],
  },
  {
    id: 'lattis-bin',
    title: 'Lattis Bin',
    img: '/project4/project4.webp',
    link: '/projects/lattis-bin',
    date: '2024',
    company: 'Lattis Bin',
    liveLink: 'https://lattisbin.vercel.app/',
    primary: '#263745',
    accentColor: '#f0f4f1',
    secondary: '#F3F5F7',
    fillColor: '#E0DFFC',
    menuColor: '#5C58EB',
    menuFontColor: '#f0f4f1',
    fluidColor: '#A3A714',
    images: [
      {
        src: '/project4/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project4/2.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/3.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/4.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project4/5.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/6.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/7.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project4/8.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project4/9.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/10.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/11.webp',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'Comprehensive waste management platform designed for Malaysian waste disposal services. Full-stack web application providing complete bin management, waste collection services, customer registration, inventory management, and order processing.',
      'Multi-role access system with admin dashboard, driver portal, and customer interface. Features real-time tracking for bin monitoring and driver location services, along with comprehensive financial management including invoicing, expense tracking, and commission management.',
      'Built with React 18, TypeScript, Vite, Tailwind CSS, shadcn/ui, Framer Motion, React Query, and modern development tools. Includes analytics & reporting, mobile integration, printing system, and deployment-ready configuration for Vercel.',
    ],
  },
  {
    id: 'yourhse-partner',
    title: 'YourHSE Partner',
    img: '/project5/project5.webp',
    link: '/projects/yourhse-partner',
    date: '2024',
    company: 'YourHSEPartner',
    liveLink: 'https://yourhsepartnerinventory.vercel.app/login',
    primary: '#000000',
    accentColor: '#f0f4f1',
    secondary: '#FAFAFA',
    fillColor: '#f2f2f2',
    menuColor: '#FFD54F',
    menuFontColor: '#000000',
    fluidColor: '#002AB0',
    images: [
      {
        src: '/project5/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/2.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/3.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project5/4.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project5/5.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/6.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/7.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/8.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/9.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project5/10.webp',
        tag: 'medium',
        isRight: false,
      },
    ],
    desc: [
      'Comprehensive Health, Safety & Environment (HSE) Management System designed for organizations to manage safety operations, inventory, and compliance requirements. Complete digital platform for safety equipment management, chemical management, and general store management.',
      'Features material issuing & requests, safety alerts & monitoring, document management, reporting & analytics, and user management with role-based access control. Built with React 18, TypeScript, Vite, shadcn/ui, Tailwind CSS, and Framer Motion.',
      'Includes React Query for server state management, React Router DOM for navigation, React Hook Form for form handling, Zod for validation, Recharts for data visualization, and additional features like toast notifications, CSV import/export, and print functionality.',
    ],
  },
  {
    id: 'jeffreyco-frontend',
    title: 'Jeffreyco Frontend',
    img: '/project1/project1.webp',
    link: '/projects/jeffreyco-frontend',
    date: '2024',
    company: 'Jeffreyco',
    liveLink: 'https://jeffrey-co.vercel.app/#signin',
    primary: '#000000',
    accentColor: '#f0f4f1',
    secondary: '#F9F9F9',
    fillColor: '#ebfaf8',
    menuColor: '#00a8c1',
    menuFontColor: '#f0f4f1',
    fluidColor: '#FF573E',
    images: [
      {
        src: '/project1/video.mp4',
        tag: 'video',
        isRight: false,
      },
      {
        src: '/project1/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project1/2.webp',
        tag: 'small',
        isRight: false,
      },
      {
        src: '/project1/7.webp',
        tag: 'small',
        isRight: true,
      },
      {
        src: '/project1/5.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project1/6.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project1/8.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project1/3.webp',
        tag: 'small',
        isRight: false,
      },
      {
        src: '/project1/4.webp',
        tag: 'small',
        isRight: true,
      },
    ],
    desc: [
      'Developed a fully responsive e-commerce frontend application using Next.js 14, TypeScript, and modern web technologies. Converted Figma designs into a production-ready web application featuring modern tech stack with Next.js 14 App Router, TypeScript, Tailwind CSS, and Redux for state management.',
      'Enhanced UX with smooth animations using Framer Motion and accessible UI components using ShadCN UI. Implemented comprehensive e-commerce features including shopping cart functionality, product browsing, and responsive design across all devices.',
    ],
  },
  {
    id: 'connie-ai',
    title: 'Connie AI',
    img: '/project2/project2.webp',
    link: '/projects/connie-ai',
    date: '2024',
    company: 'Connie AI',
    liveLink: 'https://connieai1.vercel.app/',
    primary: '#0e0063',
    accentColor: '#f0f4f1',
    secondary: '#fbfbfc',
    fillColor: '#e1e1f9',
    menuColor: '#170053',
    menuFontColor: '#f0f4f1',
    fluidColor: '#E8FFC8',
    images: [
      {
        src: '/project2/video.mp4',
        tag: 'video',
        isRight: true,
      },
      {
        src: '/project2/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project2/2.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project2/3.webp',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'Beautifully designed, modern AI SaaS landing page built with cutting-edge web technologies. Complete landing page solution for AI-powered services with focus on exceptional user experience and visual appeal using Next.js 15, TypeScript, Tailwind CSS, and React 19.',
      'Features modern UI/UX with sleek, professional design and smooth animations, fully responsive across all devices, interactive components including engaging hero section, pricing cards, and service showcases with beautiful gradient effects and parallax scrolling.',
      'Includes key sections: compelling hero section with AI-powered messaging, benefits with modern card layouts, collaboration tools integration showcase, AI service offerings with interactive elements, transparent pricing structure, and product development roadmap.',
    ],
  },
];
export default projects;
